### ISSUE TITLE
Обмен наличной гривны в Германии

### ISSUE THREAD

**Issue by ewgRa** [ua-de/refugees-common-faq#1]
Многие беженцы спрашивают про возможность обменять гривны в Германии.
Надо написать рекомендацию не брать с собой наличные гривны, так как в Германии их обменять очень проблематично. Если только через частное лицо которому нужны гривны или готов помочь.

**Comment by l13t** [comment]
В Польше, кстати, также не меняют. Официальная рекомендация от НБУ - положить деньги на счет и расплачиваться картой. Вчера общались вечером со знакомымим - пока что еще возможно поменять гривны на евро в Чехии

**Comment by ewgRa** [comment]
Написал тут https://github.com/ua-de/refugees-common-faq/blob/master/%D0%94%D0%B5%D0%BD%D1%8C%D0%B3%D0%B8%2C%20%D0%A4%D0%B8%D0%BD%D0%B0%D0%BD%D1%81%D1%8B%2C%20%D0%91%D0%B0%D0%BD%D0%BA%D0%B8.md#%D0%B3%D0%B4%D0%B5-%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C-%D0%BD%D0%B0%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B5-%D0%B3%D1%80%D0%B8%D0%B2%D0%BD%D1%8B-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8
